name = "cf_ai_oraclesage"
main = "src/index.ts"
compatibility_date = "2025-10-20"
compatibility_flags = [ "nodejs_compat" ]

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "ORACLESAGE_KV"
id = "88bd8e28af164320b2e58237fdeed05b"

[vars]
SYSTEM_PROMPT_VERSION = "1.0"
MAX_MESSAGES_PER_SESSION = 10
SESSION_TTL = 86400  # 24 hours in seconds
